version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  allowed_updates:
    - match:
      update_type: "security"
    - match:
      update_type: "geojson"
